---
# tasks file for henriquemc.jhipster

- name: install utilities
  apt: pkg={{ item }} state=present
  with_items:
     - maven
     - git
     - curl

- name: install yo
  npm: name=yo global=yes

- name: install bower
  npm: name=bower global=yes

- name: install grunt
  npm: name=grunt-cli global=yes

- name: install generator-jhipster
  npm: name=generator-jhipster global=yes
    
