---
# tasks file for henriquemc.jhipster

- name: install utilities
  apt: pkg={{ item }} state=present
  with_items:
     - maven
     - git
     - curl

- name: install yo
  npm: name=yo global=yes
  with_items:
     - yo
     - bower
     - grunt-cli
     - generator-jhipster